### ISSUE TITLE
Dependencies versions

### ISSUE THREAD

**Issue by masonlouchart** [ernsheong/lite-signal#2]
### Description
I think Polymer v2 requires `web-component-tester` v6 (instead of v4) and `webcomponentsjs` v1 (instead of v0.7) or higher.

https://www.polymer-project.org/2.0/docs/upgrade#before-you-begin

### Expected outcome

<img width="503" alt="capture d ecran 2017-12-14 a 17 11 13" src="https://user-images.githubusercontent.com/2325091/34002034-de408590-e0f1-11e7-8219-63a72c8882c8.png">

We don't need resolution for webcomponentsjs

### Actual outcome

<img width="449" alt="capture d ecran 2017-12-14 a 17 12 45" src="https://user-images.githubusercontent.com/2325091/34002123-1811324c-e0f2-11e7-86da-73a9d7063f14.png">

**Comment by ernsheong** [comment]
Addressed by https://github.com/ernsheong/lite-signal/pull/3
