### ISSUE TITLE
Does not appear to work in Firefox...with multiple subscribers

### ISSUE THREAD

**Issue by chisholmd** [ernsheong/lite-signal#4]
In FireFox if you have two elements both listening for the same signal, neither reacts to the signal.

THIS DOES NOT WORK
element-one
  < lite-signal on-lite-signal-somesignal="somefunction" >< /lite-signal >
element-two
  < lite-signal on-lite-signal-somesignal="somefunction" >< /lite-signal >

THIS DOES
element-one
  < lite-signal on-lite-signal-somesignal="somefunction" >< /lite-signal >
element-two
  < lite-signal on-lite-signal-someothersignal="somefunction" >< /lite-signal >

**Comment by ernsheong** [comment]
Thanks for the report. 

If possible, are you able to reproduce it in a bin? see https://jsbin.com/xewuraw/edit?html,output for a Polymer example.

Firefox still depends on polyfill, no native custom elements.

**Comment by chisholmd** [comment]
Well I tried to set up the bin, but I doesn't seem to work.  How do I import external components like lite-signals?.  Also, kinda of need multiple components in order to have multiple listeners.  I would be happy to share my test environment via ngrok a little later.

here is the bin I set up but I can't even get the working case to work:
https://jsbin.com/fatinar/edit?html,console,output

**Comment by ernsheong** [comment]
Thanks. I did not publish `lite-signal` to the bower registry 😅, now it is there.

Managed to reproduce the success use case in Chrome. But for some reason this bin isn't working in FF
https://jsbin.com/jihezehoko/1/edit?html,console,output

I managed to reproduce this in FF within my own app as well. I'll see if there is a fix for it

**Comment by ernsheong** [comment]
Fixed in https://github.com/ernsheong/lite-signal/commit/bd887998e780eab4bc20b6a3923aa66e758bf274

Unfortunately this means we are generating a lot of new CustomEvent objects on each event. Optimization would be the next step.

**Comment by chisholmd** [comment]
Thanks !
